FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY WebSimulateSNP42X/*.csproj .
RUN dotnet restore -r linux-arm

# copy and publish app and libraries
COPY WebSimulateSNP42X/ .
RUN dotnet publish -c release -o /app -r linux-arm --no-restore /p:PublishTrimmed=true /p:TrimMode=Link

# final stage/image
FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine-arm32v7
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["./WebSimulateSNP42X"]

EXPOSE 8080
